name: Sync to rosters-dev

on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ipx repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to rosters-dev
        env:
          SYNC_TOKEN: ${{ secrets.PAT_ROSTER_DEV }}
        run: |
          git push https://${SYNC_TOKEN}@github.com/willk71/rosters-dev.git main:main --force
